name: PHPUnit

on:
  workflow_call:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Start services
      run: |
        touch .env
        docker compose up -d

    - name: Execute tests (Unit and Feature tests)
      run: |
        # npm build
        docker compose exec web bash -c "cd /srv/ticket-sales.com &&
          ls node_modules
          \. /root/.nvm/nvm.sh &&
          npm run build"
        # test
        docker compose exec web bash -c "cd /srv/ticket-sales.com && php artisan test"
    
    - name: Stop services
      run: docker compose down -v
